# pages:
#   stage: build
#   image: node:jod-alpine
#   script:
#     - npm ci
#     - npm run build:prod
#     - cp -r dist/* public/
#     - cp dist/index.html public/404.html
#   artifacts:
#     paths:
#       - public
#   only:
#     - main
#   when: manual
